### ISSUE TITLE
unable to import * from nsnitro on python 3+

### ISSUE THREAD

**Issue by in4mashish** [eBayClassifiedsGroup/nsnitro#113]
Unable to import * from nsnitro as urllib2 is not used in python 3+. 

Need some help

**Comment by deniszh** [comment]
IIRC current codebase is not python 3 compatible. Not sure how much efforts it requires though.
Please note that official [Citrix Nitro Python API](http://docs.citrix.com/ko-kr/netscaler/11/nitro-api/nitro-python-sdk.html) doesn't support Python3 either.
So, for now - just use python2.

**Comment by favoretti** [comment]
Indeed, it's not python 3 compatible. Moreover, since Citrix currently has an official API (the one @deniszh linked above, I'm not sure it would make sense for use to keep supporting this lib. Kinda beats the purpose. We wrote this when there was no Citrix support for python at all. Unfortunately their implementation is not directly compatible with this lib, but well, they have something they support. Doing it twice doesn't make a lot of sense.

**Comment by favoretti** [comment]
That said - I'll happily merge patches that will make this lib P3 compatible if people wish to make it so. :)

**Comment by in4mashish** [comment]
Thanks favoretti and deniszh. i tried the official one provided by Citrix. it was also implemented in version 2. so had to write a small code to convert all files in package to version 3. there was a prime error with urllib2 in version 3. All is resolved now. Thanks for your assistance :)
